#!/bin/sh

crate_name=config
module_name=$crate_name

installation_type=$1

if [ $installation_type = download ]; then
    os=$2
    neovim_version=$3
    version=$4
    rm -r lua
    rm release.zip

    if [ $version = "latest" ]; then
        url=https://github.com/ModProg/config.nvim/releases/latest/download/${os}-${neovim_version}.zip
    else
        url=https://github.com/ModProg/config.nvim/releases/download/${version}/${os}-${neovim_version}.zip
    fi

    wget $url -O release.zip
    unzip release.zip
else
    neovim_version=$2
    cargo build --release -F $neovim_version --no-default-features
    mkdir lua
    cp target/release/lib${crate_name}.so lua/${module_name}.so
    cp target/release/lib${crate_name}.dylib lua/${module_name}.so
fi;
