[env]
MODULE_NAME = "config"
NIGHTLY = false

[tasks.release]
script = '''
#!@duckscript
nightly = get_env NIGHTLY
if ${nightly}
    exec --fail-on-error cargo build --release -F nightly
else
    exec --fail-on-error cargo build --release
end
mkdir lua
crate_name = get_env CARGO_MAKE_CRATE_FS_NAME
module_name = get_env MODULE_NAME
cp target/release/lib${crate_name}.so lua/${module_name}.so
'''

[tasks.install]
dependencies = ["release"]
script = '''
#!@duckscript
module_name = get_env MODULE_NAME
home = get_home_dir
cp lua/${module_name}.so ${home}/.config/nvim/lua/${module_name}.so
'''

[tasks.run]
dependencies = ["release"]
script = '''
#!@duckscript
module_name = get_env MODULE_NAME
set_env XDG_DATA_HOME ./data
exec nvim -u NONE --cmd "set runtimepath=." "+lua require'${module_name}'.load_config()"
'''

[tasks._clean]
script = '''
#!@duckscript
rm -r lua data
'''

[tasks.clean]
dependencies = ["_clean"]

