[[keys]]
modes = "n"
" o" = "m`o<Esc>``"
" O" = "m`O<Esc>``"
# figlet comments
# TODO " C" = 'gUU:FIGlet -f future<cr>:"[,"]TComment<cr>'

[[keys]]
modes = ["n", "v"]
" y" = '"+y'
" Y" = '"+Y'
" d" = '"+d'
" D" = '"+D'
" p" = '"+p'
" P" = '"+P'
# Move through wrapped lines
k = "gk"
j = "gj"
# Braces
"รถ" = "]"
"ร" = "["
"[}" = "[{"
"[]" = "[["
"[)" = "[("
# Sentence
"s" = ")"
"S" = "("
# IdentDedent
# TODO
# "<C-D>" = "call v:lua.cmp.utils.keymap.set_map(5)<CR>"

# Yaml format
# set = [
#     "expandtab",
#     "smartindent",
#     "ignorecase",
#     {mouse = "a", completeopt = ["menuone"]},
#     {"shortmess+" = "c"},
#     {shortmess = {append = "c"}},
#     {listchars = {value = {space = "_", tab = ">~"}}},
#     {listchars = {append = "c", space = "_", tab = ">~"}},
# ]

[set]
flags = [
    "expandtab",
    "smartindent",
    "number"
]
mouse = "a"
completeopt = ["menuone", "noinsert", "noselect"]

[set.shortmess]
"+" = "c"
prepend = "c"

[set.listchars.value]
space = "_"
tab = ">~"

[let.g]
asciidoctor_syntax_conceal = 1
