keys:
  - modes:
      - n
      - i
    recursive: true
    command: false
    silent: false
    unique: false
    expression: false
    leader: ""
    j: gj
    mappings:
      silent: super silent
set:
  - expandtab 
  - nonumber 
  - number: false 
  - mouse: a 
    completeopt: ["menuone"] 
  - shortmess: 
      append: c
      "+": c
      prepend: c
      "^": c
      remove: c
      "-": c
      assign: c 
      "value": c 
  - listchars:
      assign: {tab: "<->"}
  - listchars:
      tab: <->
