name: CI

on: 
  push:
  schedule: 
    - cron: '0 12 * * *'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
        neovim_version: ['0.8', '0.9', nightly]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Main
        env:
          NEOVIM_VERSION: ${{ matrix.neovim_version }}
        run: task ci --output group --output-group-begin "::group::{{.TASK}}" --output-group-end "::endgroup::"
