name: CI

on: push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
        version: ["0.7", "0.8", nightly]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: arduino/setup-task@v1

      - run: task ci --output group --output-group-begin "::group::{{.TASK}}" "::endgroup::"
