name: Release

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # os: [linux, windows, macos]
        os: [linux, macos]
        neovim_version: ["0.7", "0.8", nightly]
        include:
          - runner: ubuntu-latest
            os: linux
          # - runner: windows-latest
          #   os: windows
          - runner: macos-latest
            os: macos
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Release
        env:
          NEOVIM_VERSION: ${{ matrix.neovim_version }}
        run: task package --output group --output-group-begin "::group::{{.TASK}}" --output-group-end "::endgroup::"

      - name: Upload Artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: ${{ matrix.os }}-${{ matrix.neovim_version }}.zip
          asset_content_type: application/zip
